services:
  backend:
    container_name: rag-backend
    build:
      context: ../backend   
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend/db:/app/db
      - ../backend/vectorstore:/app/vectorstore
      - ../backend/pdf:/app/pdf
    env_file:
      - ../backend/.env
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').getcode() == 200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  frontend:
    container_name: rag-frontend    
    build:
      context: ../frontend   
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - API_URL=http://backend:8000